-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 12:07:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema FlipFit_Schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FlipFit_Schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FlipFit_Schema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `FlipFit_Schema` ;

-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`GymCentre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`GymCentre` (
  `GymId` INT NOT NULL,
  `GymName` VARCHAR(45) NOT NULL,
  `GymLocation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GymId`),
  UNIQUE INDEX `GymId_UNIQUE` (`GymId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`Role` (
  `RoleId` INT NOT NULL,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`User` (
  `UserId` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `UserEmail` VARCHAR(45) NOT NULL,
  `UserPassword` VARCHAR(45) NOT NULL,
  `UserRoleId` INT NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `UserEmailId_UNIQUE` (`UserEmail` ASC) VISIBLE,
  INDEX `FK_User_Role` (`UserRoleId` ASC) VISIBLE,
  CONSTRAINT `FK_User_Role`
    FOREIGN KEY (`UserRoleId`)
    REFERENCES `FlipFit_Schema`.`Role` (`RoleId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`Customer` (
  `CustomerId` INT NOT NULL,
  `CustomerAge` INT NOT NULL,
  `CustomerGender` VARCHAR(45) NOT NULL,
  `CustomerAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerId`),
  CONSTRAINT `FK_Customer_User`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `FlipFit_Schema`.`User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`Slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`Slot` (
  `SlotId` INT NOT NULL,
  `SlotDateTime` DATETIME NOT NULL,
  `SlotSeats` INT NOT NULL,
  `SlotSeatsLeft` INT NOT NULL,
  PRIMARY KEY (`SlotId`),
  UNIQUE INDEX `SlotId_UNIQUE` (`SlotId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`Booking` (
  `BookingId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  `GymId` INT NOT NULL,
  `SlotId` INT NOT NULL,
  `BookingStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BookingId`),
  INDEX `FK_Customer_Booking` (`CustomerId` ASC) VISIBLE,
  INDEX `FK_Slot_Booking` (`SlotId` ASC) VISIBLE,
  INDEX `FK_Booking_GymCentre` (`GymId` ASC) VISIBLE,
  CONSTRAINT `FK_Booking_GymCentre`
    FOREIGN KEY (`GymId`)
    REFERENCES `FlipFit_Schema`.`GymCentre` (`GymId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Customer_Booking`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `FlipFit_Schema`.`Customer` (`CustomerId`),
  CONSTRAINT `FK_Slot_Booking`
    FOREIGN KEY (`SlotId`)
    REFERENCES `FlipFit_Schema`.`Slot` (`SlotId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`CustomerNotifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`CustomerNotifications` (
  `CustomerId` INT NOT NULL,
  `NotificationId` INT NOT NULL,
  PRIMARY KEY (`CustomerId`, `NotificationId`),
  INDEX `FK_CustomerNotifications_Notifications` (`NotificationId` ASC) VISIBLE,
  CONSTRAINT `FK_CustomerNotifications_Customers`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `FlipFit_Schema`.`Customers` (`CustomerId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CustomerNotifications_Notifications`
    FOREIGN KEY (`NotificationId`)
    REFERENCES `FlipFit_Schema`.`Notifications` (`NotificationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`GymAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`GymAdmin` (
  `GymAdminId` INT NOT NULL,
  PRIMARY KEY (`GymAdminId`),
  UNIQUE INDEX `GymAdminId_UNIQUE` (`GymAdminId` ASC) VISIBLE,
  CONSTRAINT `FK_Admin_User`
    FOREIGN KEY (`GymAdminId`)
    REFERENCES `FlipFit_Schema`.`User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`GymOwner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`GymOwner` (
  `GymOwnerID` INT NOT NULL,
  PRIMARY KEY (`GymOwnerID`),
  UNIQUE INDEX `GymOwnerID_UNIQUE` (`GymOwnerID` ASC) VISIBLE,
  CONSTRAINT `FK_Gym_User`
    FOREIGN KEY (`GymOwnerID`)
    REFERENCES `FlipFit_Schema`.`User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`GymList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`GymList` (
  `GymOwnerId` INT NOT NULL,
  `GymId` INT NOT NULL,
  PRIMARY KEY (`GymOwnerId`, `GymId`),
  INDEX `FK_Gym_GymList` (`GymId` ASC) VISIBLE,
  CONSTRAINT `FK_Gym_GymList`
    FOREIGN KEY (`GymId`)
    REFERENCES `FlipFit_Schema`.`GymCentre` (`GymId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_GymOwner_GymList`
    FOREIGN KEY (`GymOwnerId`)
    REFERENCES `FlipFit_Schema`.`GymOwner` (`GymOwnerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`Notification` (
  `NotificationId` INT NOT NULL,
  `NotificationType` VARCHAR(45) NOT NULL,
  `NotificationTime` DATETIME NOT NULL,
  `NotificationMessage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NotificationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`Payment` (
  `PaymentId` INT NOT NULL,
  `TransactionId` INT NOT NULL,
  `Amount` INT NOT NULL,
  `PaymentDateTime` DATETIME NOT NULL,
  `CustomerId` INT NOT NULL,
  PRIMARY KEY (`PaymentId`),
  UNIQUE INDEX `TransactionId_UNIQUE` (`TransactionId` ASC) VISIBLE,
  INDEX `FK_Customer_Payment` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `FK_Customer_Payment`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `FlipFit_Schema`.`Customer` (`CustomerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `FlipFit_Schema`.`SlotList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FlipFit_Schema`.`SlotList` (
  `SlotId` INT NOT NULL,
  `GymId` INT NOT NULL,
  PRIMARY KEY (`SlotId`, `GymId`),
  INDEX `FK_Gym_SlotList` (`GymId` ASC) VISIBLE,
  CONSTRAINT `FK_Gym_SlotList`
    FOREIGN KEY (`GymId`)
    REFERENCES `FlipFit_Schema`.`GymCentre` (`GymId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Slot_SlotList`
    FOREIGN KEY (`SlotId`)
    REFERENCES `FlipFit_Schema`.`Slot` (`SlotId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
